[tool.bumpversion]
current_version = "2.0.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "chore: bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = [
    "git config --global user.email \"erickmaria08@gmail.com\"",
    "git config --global user.name \"Erick Maria\"",
    "git --version",
    "git config --list",
]
pre_commit_hooks = ["npm version $BVHOOK_CURRENT_VERSION --no-git-tag-version"]
post_commit_hooks = ["echo Done"]


[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "Unreleased"
replace = """Unreleased

## v{new_version} - {now:%Y-%m-%d}"""