name: CI

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Remote Branches
        run: git fetch origin
      
      - name: Check for Changelog Changes
        id: changelog
        run: |
          git diff --name-only origin/${{ github.base_ref }} -- CHANGELOG.md
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - run: npm install
    - name: Run Lint
      run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Run Build
      run: npm run build

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
      - name: Run Typecript Coverage
        run: npm run ts-coverage
