name: Update version and create Release's PR Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Update the version
        id: update_version
        run: |
          echo "version=$(npm version ${{ github.event.inputs.version }} --no-git-tag-version)" >> $GITHUB_OUTPUT

      - name: Update Changelog
        id: update_changelog
        run: |
          current_date=$(date +'%Y-%m-%d') 
          sed -i "s/Unreleased/${{ steps.update_version.outputs.version }} - ${current_date}/g" CHANGELOG.md
          sed -i '1s/$/\n\n## Unreleased/' CHANGELOG.md 

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release: ${{ steps.update_version.outputs.version }} Pull Request"
          body: "This pull request contains the updated package.json with the new release version"
          base: main
